Table parkArea {
  id integer [primary key]
  name varchar
  guestId integer
}
Table services {
  id integer [primary key]
  name varchar
}
Table guests {
  id integer [primary key]
  name varchar
}
Table areaServices {
  servicesId int (fk)
  areaId int  (fk)
  areaServices int [primary key]
}
Ref: "services"."id" < "areaServices"."servicesId"
Ref: "parkArea"."id" < "areaServices"."areaId"
Ref: "parkArea"."guestId" < "guests"."id"